export type {
  Priority,
  Estimate,
  CardStatus,
  Card,
  CardRunInTarget,
  Column,
  Board,
  CanvasData,
  ClipboardPasteInspectionResult,
  CardInput,
  CardCreateInput,
  CardUpdateResult,
  CardCreatePlacement,
  CalendarOccurrence,
  CardOccurrenceActionInput,
  CardOccurrenceUpdateInput,
  OccurrenceActionSource,
  OccurrenceEditScope,
  MoveCardInput,
  MoveCardToProjectInput,
  MoveCardToProjectResult,
  MoveCardsInput,
  BlockDropImportInput,
  BlockDropImportResult,
  BlockDropImportSourceUpdate,
  CardDropMoveToEditorInput,
  CardDropMoveToEditorResult,
  RecurrenceConfig,
  RecurrenceEndCondition,
  RecurrenceFrequency,
  ReminderConfig,
  OccurrenceTimingUpdates,
  Project,
  ProjectInput,
  CodexConnectionState,
  CodexAccountSnapshot,
  CodexModelOption,
  CodexCollaborationModeKind,
  CodexCollaborationModePreset,
  CodexRateLimitsSnapshot,
  CodexReasoningEffort,
  CodexReasoningEffortOption,
  CodexThreadSettings,
  CodexThreadStartForCardInput,
  CodexTurnStartOptions,
  CodexPermissionMode,
  CodexThreadSummary,
  CodexThreadDetail,
  CodexThreadTokenUsage,
  CodexTokenUsageBreakdown,
  CodexTurnSummary,
  CodexThreadStartProgressPhase,
  CodexItemNormalizedKind,
  CodexItemStatus,
  CodexToolCallSubtype,
  CodexToolCallView,
  CodexCommandAction,
  CodexItemView,
  CodexApprovalRequest,
  CodexApprovalDecision,
  CodexUserInputRequest,
  CodexPlanImplementationRequest,
  CodexEvent,
  BackupRecord,
  BackupSettings,
  BackupSettingsEnvOverrides,
  HistorySettings,
  HistorySettingsEnvOverrides,
  ThreadNotificationSettings,
  CreateBackupInput,
  RestoreBackupInput,
  RestoreBackupResult,
  ManagedWorktreeRecord,
  WorktreeEnvironmentOption,
  WorktreeStartMode,
  UpdateBackupSettingsInput,
  UpdateHistorySettingsInput,
  UpdateThreadNotificationSettingsInput,
  UploadedResourceAsset,
} from "../../shared/types";
export type {
  WorkbenchRecentCardSession,
  WorkbenchResumeCardStageState,
  WorkbenchResumeSnapshot,
  WorkbenchResumeStageId,
  WorkbenchResumeStageNavDirection,
  WorkbenchResumeView,
} from "../../shared/workbench-resume";

import type { Estimate, CardUpdateResult } from "../../shared/types";

export const estimateStyles: Record<Estimate, { label: string; className: string }> = {
  xl: { label: "XL", className: "bg-[var(--red-bg)] text-[var(--red-text)]" },
  l: { label: "L", className: "bg-[var(--orange-bg)] text-[var(--orange-text)]" },
  m: { label: "M", className: "bg-[var(--yellow-bg)] text-[var(--yellow-text)]" },
  s: { label: "S", className: "bg-[var(--green-bg)] text-[var(--green-text)]" },
  xs: { label: "XS", className: "bg-[var(--blue-bg)] text-[var(--blue-text)]" },
};

export const estimateOptions: Array<{ value: "none" | Estimate; label: string }> = [
  { value: "none", label: "None" },
  ...Object.entries(estimateStyles).map(([value, { label }]) => ({
    value: value as Estimate,
    label,
  })),
];

export type CardUpdateMutationResult = CardUpdateResult | {
  status: "error";
  error: string;
};
