import type { ReleaseBundleManifest } from "./bundle";
import { normalizeStableVersion } from "./model";

export interface HomebrewCaskOptions {
  readonly arm64Sha256: string;
  readonly bundleId?: string;
  readonly owner?: string;
  readonly repo?: string;
  readonly version: string;
  readonly x64Sha256: string;
}

const normalizeSha = (value: string, label: string): string => {
  const normalized = value.trim().toLowerCase();
  if (!/^[a-f0-9]{64}$/.test(normalized)) throw new Error(`${label} must be a SHA-256 digest.`);
  return normalized;
};

export function generateHomebrewCask(options: HomebrewCaskOptions): string {
  const version = normalizeStableVersion(options.version);
  const arm64 = normalizeSha(options.arm64Sha256, "arm64 checksum");
  const x64 = normalizeSha(options.x64Sha256, "x64 checksum");
  const owner = options.owner?.trim() || "junyudev";
  const repo = options.repo?.trim() || "nodex";
  const bundleId = options.bundleId?.trim() || "app.jyu.nodex";
  const releaseBase = `https://github.com/${owner}/${repo}/releases/download/v#{version}`;
  return `# This file is generated by Nodex's release Module.
# Do not edit release values manually.

cask "nodex" do
  version "${version}"

  on_arm do
    sha256 "${arm64}"

    url "${releaseBase}/Nodex-latest-arm64.dmg",
        verified: "github.com/${owner}/${repo}/"
  end
  on_intel do
    sha256 "${x64}"

    url "${releaseBase}/Nodex-latest-x64.dmg",
        verified: "github.com/${owner}/${repo}/"
  end

  name "Nodex"
  desc "Block-based Agent Orchestrator"
  homepage "https://nodex.jyu.app/"

  livecheck do
    url "https://github.com/${owner}/${repo}"
    strategy :github_latest
  end

  auto_updates true
  depends_on macos: :sequoia

  app "Nodex.app"
  binary "#{appdir}/Nodex.app/Contents/Resources/bin/nodex", target: "nodex"

  zap trash: [
    "~/Library/Preferences/${bundleId}.plist",
    "~/Library/Saved Application State/${bundleId}.savedState",
  ]
end
`;
}

export function generateHomebrewCaskFromBundle(bundle: ReleaseBundleManifest): string {
  const arm64 = bundle.assets.find(
    (asset) => asset.role === "dmg" && asset.architecture === "arm64",
  );
  const x64 = bundle.assets.find((asset) => asset.role === "dmg" && asset.architecture === "x64");
  if (!arm64 || !x64) throw new Error("Release bundle does not contain both canonical DMGs.");
  return generateHomebrewCask({
    arm64Sha256: arm64.sha256,
    version: bundle.version,
    x64Sha256: x64.sha256,
  });
}
