import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { parse as parseToml } from "smol-toml";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, expect, test } from "vite-plus/test";
import {
  checkWorktreeReleaseTransition,
  detectReleaseTransition,
  inspectReleaseSource,
  inspectReleaseSourceAtRef,
  prepareReleaseSource,
} from "./source";

const PACKAGE_NAMES = [
  "nodex-browser-profile-helper",
  "nodex-cli",
  "nodex-core",
  "nodex-core-contracts",
  "nodex-core-protocol",
  "nodex-core-server",
  "new-workspace-member",
] as const;

let fixture = "";

const git = (...args: string[]): string =>
  execFileSync("git", args, {
    cwd: fixture,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  }).trim();

const writeFixture = (version = "0.1.10"): void => {
  writeFileSync(
    join(fixture, "package.json"),
    `${JSON.stringify({ name: "nodex", version }, null, 2)}\n`,
  );
  writeFileSync(
    join(fixture, "Cargo.toml"),
    `[workspace]\nmembers = ${JSON.stringify(PACKAGE_NAMES.map((name) => `crates/${name}`))}\n\n[workspace.package]\nversion = "${version}"\n`,
  );
  for (const name of PACKAGE_NAMES) {
    mkdirSync(join(fixture, "crates", name), { recursive: true });
    writeFileSync(
      join(fixture, "crates", name, "Cargo.toml"),
      `[package]\nname = "${name}"\nversion.workspace = true\n`,
    );
  }
  writeFileSync(
    join(fixture, "Cargo.lock"),
    `# This file is automatically @generated by Cargo.\nversion = 4\n\n${PACKAGE_NAMES.map(
      (name) => `[[package]]\nname = "${name}"\nversion = "${version}"\n`,
    ).join("\n")}`,
  );
  writeFileSync(
    join(fixture, "CHANGELOG.md"),
    `# Changelog\n\n## [Unreleased]\n\n### Added\n- Added a verified release flow.\n\n## [${version}] - 2026-05-03\n\n### Added\n- Previous release.\n`,
  );
};

beforeEach(() => {
  fixture = mkdtempSync(join(tmpdir(), "nodex-release-source-"));
  writeFixture();
  git("init");
  git("config", "user.name", "Nodex Test");
  git("config", "user.email", "nodex@example.com");
  git("add", ".");
  git("commit", "-m", "chore: seed release source");
});

afterEach(() => rmSync(fixture, { recursive: true, force: true }));

test("prepareReleaseSource synchronizes package, Cargo, lock, and changelog without committing", () => {
  const prepared = prepareReleaseSource({
    cwd: fixture,
    date: "2026-07-31",
    validateCargoMetadata: false,
    version: "0.2.0",
  });
  const snapshot = inspectReleaseSource(fixture);

  expect(prepared).toMatchObject({ tag: "v0.2.0", version: "0.2.0" });
  expect(snapshot.packageVersion).toBe("0.2.0");
  expect(snapshot.cargoVersion).toBe("0.2.0");
  const lock = parseToml(readFileSync(join(fixture, "Cargo.lock"), "utf8"));
  expect(lock.package).toEqual(PACKAGE_NAMES.map((name) => ({ name, version: "0.2.0" })));
  expect(snapshot.changelog).toContain("## [0.2.0] - 2026-07-31");
  expect(git("log", "-1", "--format=%s")).toBe("chore: seed release source");
  expect(git("diff", "--name-only").split("\n").sort()).toEqual([
    "CHANGELOG.md",
    "Cargo.lock",
    "Cargo.toml",
    "package.json",
  ]);
});

test.each(["missing", "stale", "duplicate", "registry"])(
  "rejects a %s lock entry for a newly added workspace member",
  (kind) => {
    const path = join(fixture, "Cargo.lock");
    const entry = '[[package]]\nname = "new-workspace-member"\nversion = "0.1.10"\n';
    const replacement =
      kind === "missing"
        ? ""
        : kind === "stale"
          ? entry.replace("0.1.10", "0.1.9")
          : kind === "duplicate"
            ? `${entry}\n${entry}`
            : `${entry}source = "registry+https://example.invalid/index"\n`;
    writeFileSync(path, readFileSync(path, "utf8").replace(entry, replacement));
    expect(() => inspectReleaseSource(fixture)).toThrow(/new-workspace-member/);
  },
);

test("historical inspection uses member manifests from that commit, not the worktree", () => {
  writeFileSync(
    join(fixture, "crates/new-workspace-member/Cargo.toml"),
    '[package]\nname = "renamed-member"\nversion.workspace = true\n',
  );
  expect(() => inspectReleaseSource(fixture)).toThrow("renamed-member");
  expect(inspectReleaseSourceAtRef(fixture, "HEAD").packageVersion).toBe("0.1.10");
});

test.each(["../outside", "crates/*", "/absolute"])(
  "rejects unsupported workspace member %s before reading it",
  (member) => {
    const path = join(fixture, "Cargo.toml");
    writeFileSync(
      path,
      readFileSync(path, "utf8").replace(/members = .*/, `members = ${JSON.stringify([member])}`),
    );
    expect(() => inspectReleaseSource(fixture)).toThrow("explicit repository-relative");
  },
);

test("workspace members must inherit the release version", () => {
  writeFileSync(
    join(fixture, "crates/new-workspace-member/Cargo.toml"),
    '[package]\nname = "new-workspace-member"\nversion = "0.1.10"\n',
  );
  expect(() => inspectReleaseSource(fixture)).toThrow("inherited workspace version");
});

test("preparation preserves unrelated path dependency versions", () => {
  const lock = join(fixture, "Cargo.lock");
  writeFileSync(
    lock,
    `${readFileSync(lock, "utf8")}\n[[package]]\nname = "external-path-dependency"\nversion = "8.0.0"\n`,
  );
  git("add", ".");
  git("commit", "-m", "test: add path dependency");
  prepareReleaseSource({
    cwd: fixture,
    date: "2026-09-20",
    validateCargoMetadata: false,
    version: "0.2.0",
  });
  const parsed = parseToml(readFileSync(lock, "utf8"));
  expect(parsed.package).toContainEqual({ name: "external-path-dependency", version: "8.0.0" });
});

test("preparation preserves a different-version path dependency with the same name", () => {
  const lock = join(fixture, "Cargo.lock");
  writeFileSync(
    lock,
    `${readFileSync(lock, "utf8")}\n[[package]]\nname = "new-workspace-member"\nversion = "8.0.0"\n`,
  );
  git("add", ".");
  git("commit", "-m", "test: add same-name path dependency");
  prepareReleaseSource({
    cwd: fixture,
    date: "2026-09-20",
    validateCargoMetadata: false,
    version: "0.2.0",
  });
  const parsed = parseToml(readFileSync(lock, "utf8"));
  expect(parsed.package).toContainEqual({ name: "new-workspace-member", version: "8.0.0" });
  expect(parsed.package).toContainEqual({ name: "new-workspace-member", version: "0.2.0" });
});

test("same-name and same-version registry dependencies do not own the release version", () => {
  const lock = join(fixture, "Cargo.lock");
  const remote = {
    name: "new-workspace-member",
    version: "0.1.10",
    source: "registry+https://example.invalid/index",
  };
  writeFileSync(
    lock,
    `${readFileSync(lock, "utf8")}\n[[package]]\nname = "${remote.name}"\nversion = "${remote.version}"\nsource = "${remote.source}"\n`,
  );
  git("add", ".");
  git("commit", "-m", "test: add same-identity registry dependency");
  prepareReleaseSource({
    cwd: fixture,
    date: "2026-09-20",
    validateCargoMetadata: false,
    version: "0.2.0",
  });
  expect(parseToml(readFileSync(lock, "utf8")).package).toContainEqual(remote);
  expect(parseToml(readFileSync(lock, "utf8")).package).toContainEqual({
    name: remote.name,
    version: "0.2.0",
  });
});

test.each([
  "dependencies",
  "dev-dependencies",
  "build-dependencies",
  "target.'cfg(unix)'.dependencies",
])("rejects implicit workspace enrollment through %s", (kind) => {
  const manifest = join(fixture, "crates/new-workspace-member/Cargo.toml");
  writeFileSync(
    manifest,
    `${readFileSync(manifest, "utf8")}\n[${kind}]\nunlisted = { path = "../unlisted" }\n`,
  );
  expect(() => inspectReleaseSource(fixture)).toThrow("must be an explicit workspace member");
  git("add", ".");
  git("commit", "-m", "test: add implicit workspace dependency");
  expect(() => inspectReleaseSourceAtRef(fixture, "HEAD")).toThrow(
    "must be an explicit workspace member",
  );
});

test("inherited path dependencies resolve from the workspace root", () => {
  const root = join(fixture, "Cargo.toml");
  const manifest = join(fixture, "crates/new-workspace-member/Cargo.toml");
  writeFileSync(
    manifest,
    `${readFileSync(manifest, "utf8")}\n[dependencies]\ncore.workspace = true\n`,
  );
  writeFileSync(
    root,
    `${readFileSync(root, "utf8")}\n[workspace.dependencies]\ncore = { path = "crates/nodex-core" }\n`,
  );
  expect(inspectReleaseSource(fixture).packageVersion).toBe("0.1.10");
  writeFileSync(
    root,
    readFileSync(root, "utf8").replace('path = "crates/nodex-core"', 'path = "crates/unlisted"'),
  );
  expect(() => inspectReleaseSource(fixture)).toThrow("must be an explicit workspace member");
});

test("the explicit-member guard rejects a real Cargo implicitly enrolled crate", () => {
  for (const name of [...PACKAGE_NAMES, "unlisted"]) {
    mkdirSync(join(fixture, "crates", name, "src"), { recursive: true });
    writeFileSync(join(fixture, "crates", name, "src/lib.rs"), "");
  }
  writeFileSync(
    join(fixture, "crates/unlisted/Cargo.toml"),
    '[package]\nname = "unlisted"\nversion.workspace = true\n',
  );
  const manifest = join(fixture, "crates/new-workspace-member/Cargo.toml");
  writeFileSync(
    manifest,
    `${readFileSync(manifest, "utf8")}\n[dependencies]\nunlisted = { path = "../unlisted" }\n`,
  );
  const metadata = JSON.parse(
    execFileSync("cargo", ["metadata", "--offline", "--no-deps", "--format-version", "1"], {
      cwd: fixture,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
      timeout: 15000,
    }),
  ) as { workspace_members: string[] };
  expect(metadata.workspace_members).toHaveLength(PACKAGE_NAMES.length + 1);
  expect(() => inspectReleaseSource(fixture)).toThrow("must be an explicit workspace member");
});

test("worktree inspection rejects member manifests resolving outside the repository", () => {
  const outside = mkdtempSync(join(tmpdir(), "nodex-outside-manifest-"));
  try {
    const manifest = join(fixture, "crates/new-workspace-member/Cargo.toml");
    const external = join(outside, "Cargo.toml");
    writeFileSync(external, readFileSync(manifest, "utf8"));
    rmSync(manifest);
    symlinkSync(external, manifest);
    expect(() => inspectReleaseSource(fixture)).toThrow("regular file within the worktree");
  } finally {
    rmSync(outside, { recursive: true, force: true });
  }
});

test("worktree inspection accepts contained manifest links and rejects non-regular targets", () => {
  const manifest = join(fixture, "crates/new-workspace-member/Cargo.toml");
  const contained = join(fixture, "member.toml");
  writeFileSync(contained, readFileSync(manifest, "utf8"));
  rmSync(manifest);
  symlinkSync(contained, manifest);
  expect(inspectReleaseSource(fixture).packageVersion).toBe("0.1.10");
  rmSync(manifest);
  mkdirSync(manifest);
  expect(() => inspectReleaseSource(fixture)).toThrow("regular file within the worktree");
});

test("checkWorktreeReleaseTransition accepts exactly the metadata-only release diff", () => {
  prepareReleaseSource({
    cwd: fixture,
    date: "2026-07-31",
    validateCargoMetadata: false,
    version: "0.2.0",
  });
  expect(checkWorktreeReleaseTransition(fixture, "HEAD")).toMatchObject({
    baseVersion: "0.1.10",
    shouldRelease: true,
    tag: "v0.2.0",
    version: "0.2.0",
  });
});

test("detectReleaseTransition ignores an identity repair without an app version change", () => {
  writeFileSync(join(fixture, "README.md"), "documentation\n");
  git("add", "README.md");
  git("commit", "-m", "docs: add readme");
  expect(detectReleaseTransition(fixture, "HEAD^", "HEAD")).toEqual({
    shouldRelease: false,
    version: "0.1.10",
  });
});

test("release transition rejects source changes mixed into the metadata commit", () => {
  prepareReleaseSource({
    cwd: fixture,
    date: "2026-07-31",
    validateCargoMetadata: false,
    version: "0.2.0",
  });
  writeFileSync(join(fixture, "README.md"), "mixed source change\n");
  expect(() => checkWorktreeReleaseTransition(fixture, "HEAD")).toThrow("may change only");
});

test("release preparation rejects a dirty worktree before writing", () => {
  writeFileSync(
    join(fixture, "CHANGELOG.md"),
    `${readFileSync(join(fixture, "CHANGELOG.md"), "utf8")}dirty\n`,
  );
  expect(() =>
    prepareReleaseSource({
      cwd: fixture,
      date: "2026-07-31",
      validateCargoMetadata: false,
      version: "0.2.0",
    }),
  ).toThrow("clean git worktree");
});
