import type { CodexRendererNativeRequestOptions } from "./codex-renderer-request";

const REQUEST_SOURCES: Readonly<Record<string, string>> = {
  "account/login/cancel": `account`,
  "account/login/start": `account`,
  "account/logout": `account`,
  "account/rateLimitResetCredit/consume": `account`,
  "account/rateLimits/read": `account`,
  "account/read": `account`,
  "account/usage/read": `account`,
  "app/list": `apps`,
  "app/installed": `apps`,
  "app/read": `apps`,
  "collaborationMode/list": `collaboration_modes`,
  "command/exec": `command`,
  "config/batchWrite": `config`,
  "config/mcpServer/reload": `config`,
  "config/read": `config`,
  "config/value/write": `config`,
  "configRequirements/read": `config`,
  "environment/info": `filesystem`,
  "experimentalFeature/enablement/set": `features`,
  "experimentalFeature/list": `features`,
  "externalAgentConfig/detect": `external_agent_config`,
  "externalAgentConfig/import": `external_agent_config`,
  "externalAgentConfig/import/readHistories": `external_agent_config`,
  "feedback/upload": `feedback`,
  "fs/copy": `filesystem`,
  "fs/createDirectory": `filesystem`,
  "fs/getMetadata": `filesystem`,
  "fs/readDirectory": `filesystem`,
  "fs/readFile": `filesystem`,
  "fs/remove": `filesystem`,
  "fs/unwatch": `filesystem`,
  "fs/watch": `filesystem`,
  "fs/writeFile": `filesystem`,
  "fuzzyFileSearch/sessionStart": `fuzzy_file_search`,
  "fuzzyFileSearch/sessionStop": `fuzzy_file_search`,
  "fuzzyFileSearch/sessionUpdate": `fuzzy_file_search`,
  "hooks/list": `hooks`,
  "interactive/liveSessions/list": `interactive_sessions`,
  "interactive/session/upload": `feedback`,
  "interactive/sessionSandbox/list": `interactive_sessions`,
  "interactive/sessionSandbox/read": `interactive_sessions`,
  "marketplace/add": `marketplace`,
  "marketplace/remove": `marketplace`,
  "marketplace/upgrade": `marketplace`,
  "mcpServer/oauth/login": `mcp`,
  "mcpServer/event/stream/start": `mcp`,
  "mcpServer/event/stream/stop": `mcp`,
  "mcpServer/resource/read": `mcp`,
  "mcpServer/tool/call": `mcp`,
  "mcpServerStatus/list": `mcp`,
  "memory/reset": `memory`,
  "memory/status": `memory`,
  "mock/experimentalMethod": `mock`,
  "model/list": `models`,
  "modelProvider/capabilities/read": `models`,
  "permissionProfile/list": `permissions`,
  "plugin/install": `plugins`,
  "plugin/installed": `plugins`,
  "plugin/list": `plugins`,
  "plugin/read": `plugins`,
  "plugin/reconcile": `plugins`,
  "plugin/search": `plugins`,
  "plugin/share/delete": `plugins`,
  "plugin/share/list": `plugins`,
  "plugin/share/save": `plugins`,
  "plugin/share/updateTargets": `plugins`,
  "plugin/skill/read": `plugins`,
  "plugin/uninstall": `plugins`,
  "process/kill": `process`,
  "process/resizePty": `process`,
  "process/spawn": `process`,
  "process/writeStdin": `process`,
  "project/create": `thread`,
  "project/delete": `thread`,
  "project/import": `thread`,
  "project/list": `thread`,
  "project/move": `thread`,
  "project/read": `thread`,
  "project/update": `thread`,
  "remoteControl/client/list": `remote_control`,
  "remoteControl/client/revoke": `remote_control`,
  "remoteControl/disable": `remote_control`,
  "remoteControl/enable": `remote_control`,
  "remoteControl/pairing/start": `remote_control`,
  "remoteControl/pairing/status": `remote_control`,
  "remoteControl/status/read": `remote_control`,
  "review/start": `review`,
  "skills/config/write": `skills`,
  "skills/extraRoots/set": `skills`,
  "skills/list": `skills`,
  "thread/approveGuardianDeniedAction": `thread`,
  "thread/archive": `thread`,
  "thread/backgroundTerminals/clean": `thread`,
  "thread/compact/start": `thread`,
  "thread/delete": `thread`,
  "thread/fork": `thread`,
  "thread/goal/clear": `thread`,
  "thread/goal/get": `thread`,
  "thread/goal/set": `thread`,
  "thread/inject_items": `thread`,
  "thread/items/list": `thread`,
  "thread/list": `thread`,
  "thread/loaded/list": `thread`,
  "thread/memoryMode/set": `thread`,
  "thread/metadata/update": `thread`,
  "thread/name/set": `thread`,
  "thread/queue/add": `thread`,
  "thread/queue/delete": `thread`,
  "thread/queue/list": `thread`,
  "thread/queue/reorder": `thread`,
  "thread/queue/start": `thread`,
  "thread/queue/update": `thread`,
  "thread/read": `thread`,
  "thread/resume": `thread`,
  "thread/revert": `thread`,
  "thread/rollback": `thread`,
  "thread/search": `thread`,
  "thread/searchOccurrences": `thread`,
  "thread/section/move": `thread`,
  "thread/settings/update": `thread`,
  "thread/shellCommand": `thread`,
  "thread/start": `thread`,
  "thread/startAeon": `thread`,
  "thread/stop": `thread`,
  "thread/timeline/list": `thread`,
  "thread/turns/list": `thread`,
  "thread/unarchive": `thread`,
  "thread/unsubscribe": `thread`,
  "threadSection/create": `thread`,
  "threadSection/delete": `thread`,
  "threadSection/list": `thread`,
  "threadSection/update": `thread`,
  "turn/interrupt": `turn`,
  "turn/settings/update": `turn`,
  "turn/start": `turn`,
  "turn/steer": `turn`,
  "windowsSandbox/readiness": `windows_sandbox`,
  "windowsSandbox/setupStart": `windows_sandbox`,
  fuzzyFileSearch: `fuzzy_file_search`,
  getAuthStatus: `account`,
  getConversationSummary: `conversation_summary`,
  gitDiffToRemote: `git`,
  initialize: `initialization`,
};

const CRITICAL_METHODS = new Set([
  "thread/approveGuardianDeniedAction",
  "thread/resume",
  "thread/start",
  "turn/interrupt",
  "turn/start",
  "turn/steer",
]);
const BACKGROUND_METHODS = new Set([
  "app/installed",
  "app/list",
  "app/read",
  "collaborationMode/list",
  "config/read",
  "configRequirements/read",
  "experimentalFeature/list",
  "hooks/list",
  "mcpServerStatus/list",
  "model/list",
  "permissionProfile/list",
  "plugin/list",
  "skills/list",
]);

export function codexRequestSource(method: string, requested?: string | null): string {
  return requested ?? REQUEST_SOURCES[method] ?? "thread";
}

export function codexRendererRequestPriority(
  method: string,
  requested?: CodexRendererNativeRequestOptions["priority"],
): NonNullable<CodexRendererNativeRequestOptions["priority"]> {
  if (requested !== undefined) return requested;
  if (CRITICAL_METHODS.has(method)) return "critical";
  return BACKGROUND_METHODS.has(method) ? "background" : "interactive";
}
