import type { CodexItemView, CodexTranscriptEntry, CodexTranscriptEntrySource } from "./types";

export function projectCodexItemViewToTranscriptEntry(
  item: CodexItemView,
  source: CodexTranscriptEntrySource,
  sequence: number,
): CodexTranscriptEntry {
  return {
    threadId: item.threadId,
    turnId: item.turnId,
    entryId: item.itemId,
    itemId: item.itemId,
    rawItemId: item.rawItemId,
    rawItemType: item.rawItemType,
    type: item.type,
    kind: item.normalizedKind,
    semanticKind: item.semanticKind,
    assistantPhase: item.assistantPhase,
    timeLabel: item.timeLabel,
    status: item.status,
    role: item.role,
    source,
    sequence,
    toolCall: item.toolCall,
    mcpToolCall: item.mcpToolCall,
    dynamicToolCall: item.dynamicToolCall,
    automationUpdate: item.automationUpdate,
    webSearch: item.webSearch,
    generatedImage: item.generatedImage,
    subagentActivity: item.subagentActivity,
    contextCompaction: item.contextCompaction,
    requestId: item.requestId,
    cmd: item.cmd,
    callId: item.callId,
    commandExecutionItemId: item.commandExecutionItemId,
    command: item.command,
    cwd: item.cwd,
    processId: item.processId,
    commandActions: item.commandActions,
    aggregatedOutput: item.aggregatedOutput,
    exitCode: item.exitCode,
    durationMs: item.durationMs,
    startedAtMs: item.startedAtMs,
    executionStatus: item.executionStatus,
    parsedCmd: item.parsedCmd,
    approvalRequestId: item.approvalRequestId,
    approvalReason: item.approvalReason,
    networkApprovalContext: item.networkApprovalContext,
    proposedExecpolicyAmendment: item.proposedExecpolicyAmendment,
    proposedNetworkPolicyAmendments: item.proposedNetworkPolicyAmendments,
    grantRoot: item.grantRoot,
    fileChange: item.fileChange,
    markdownText: item.markdownText,
    goal: item.goal,
    hookFeedback: item.hookFeedback,
    imageViewPaths: item.imageViewPaths,
    userAttachments: item.userAttachments,
    commentAttachments: item.commentAttachments,
    deliveryStatus: item.deliveryStatus,
    steeringStatus: item.steeringStatus,
    steeringInput: item.steeringInput,
    steeringCompareKey: item.steeringCompareKey,
    steeringRestoreMessage: item.steeringRestoreMessage,
    steeringTargetTurnId: item.steeringTargetTurnId,
    steeringTargetTurnStartedAtMs: item.steeringTargetTurnStartedAtMs,
    acceptedUserMessageItemId: item.acceptedUserMessageItemId,
    additionalDetails: item.additionalDetails,
    willRetry: item.willRetry,
    asyncQuestion: item.asyncQuestion,
    questionReplies: item.questionReplies,
    userInputQuestions: item.userInputQuestions,
    userInputAnswers: item.userInputAnswers,
    rawItem: item.rawItem,
    createdAt: item.createdAt,
    updatedAt: item.updatedAt,
  };
}
