import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

type GenerateHomebrewCaskOptions = {
  arm64Sha256: string;
  bundleId: string;
  owner: string;
  outputPath: string | null;
  repo: string;
  version: string;
  x64Sha256: string;
};

type CliOptions = GenerateHomebrewCaskOptions;

const defaultOptions: Omit<CliOptions, "arm64Sha256" | "outputPath" | "version" | "x64Sha256"> = {
  bundleId: "app.jyu.nodex",
  owner: "Asphocarp",
  repo: "nodex",
};

function normalizeSha256(value: string, label: string): string {
  const normalized = value.trim().toLowerCase();

  if (!/^[a-f0-9]{64}$/.test(normalized)) {
    throw new Error(`Expected ${label} to be a 64-character SHA256 hex string.`);
  }

  return normalized;
}

function normalizeRequiredValue(value: string | null, label: string): string {
  const normalized = value?.trim() ?? "";

  if (normalized.length === 0) {
    throw new Error(`Missing required value for ${label}.`);
  }

  return normalized;
}

export function generateHomebrewCask(options: GenerateHomebrewCaskOptions): string {
  const version = normalizeRequiredValue(options.version, "--version");
  const arm64Sha256 = normalizeSha256(options.arm64Sha256, "--arm64-sha256");
  const x64Sha256 = normalizeSha256(options.x64Sha256, "--x64-sha256");
  const bundleId = normalizeRequiredValue(options.bundleId, "--bundle-id");
  const owner = normalizeRequiredValue(options.owner, "--owner");
  const repo = normalizeRequiredValue(options.repo, "--repo");
  const releaseBaseUrl = `https://github.com/${owner}/${repo}/releases/download/v#{version}`;
  const verifiedHost = `github.com/${owner}/${repo}/`;
  const homepage = `https://github.com/${owner}/${repo}`;

  return `# This file is generated by scripts/generate-homebrew-cask.ts.
# Do not edit release values manually; CI rewrites the tap cask on every tagged release.

cask "nodex" do
  version "${version}"

  on_arm do
    sha256 "${arm64Sha256}"

    url "${releaseBaseUrl}/Nodex-#{version}-arm64.dmg",
        verified: "${verifiedHost}"
  end

  on_intel do
    sha256 "${x64Sha256}"

    url "${releaseBaseUrl}/Nodex-#{version}-x64.dmg",
        verified: "${verifiedHost}"
  end

  name "Nodex"
  desc "Block-based Agent Orchestrator"
  homepage "${homepage}"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  depends_on macos: ">= :monterey"

  app "Nodex.app"

  zap trash: [
    "~/.nodex",
    "~/Library/Application Support/nodex",
    "~/Library/Preferences/${bundleId}.plist",
    "~/Library/Saved Application State/${bundleId}.savedState",
  ]
end
`;
}

function writeOptionalFile(outputPath: string | null, content: string): void {
  if (!outputPath) {
    process.stdout.write(content);
    return;
  }

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content, "utf8");
}

function parseCliOptions(argv: string[]): CliOptions {
  let version: string | null = null;
  let arm64Sha256: string | null = null;
  let x64Sha256: string | null = null;
  let outputPath: string | null = null;
  let owner = defaultOptions.owner;
  let repo = defaultOptions.repo;
  let bundleId = defaultOptions.bundleId;

  for (let index = 0; index < argv.length; ) {
    const argument = argv[index];

    if (argument === "--") {
      index += 1;
      continue;
    }

    if (!argument.startsWith("--")) {
      throw new Error(`Unexpected argument "${argument}".`);
    }

    const value = argv[index + 1];

    if (!value || value.startsWith("--")) {
      throw new Error(`Missing value for ${argument}.`);
    }

    switch (argument) {
      case "--version":
        version = value;
        break;
      case "--arm64-sha256":
        arm64Sha256 = value;
        break;
      case "--x64-sha256":
        x64Sha256 = value;
        break;
      case "--output":
        outputPath = resolve(value);
        break;
      case "--owner":
        owner = value;
        break;
      case "--repo":
        repo = value;
        break;
      case "--bundle-id":
        bundleId = value;
        break;
      default:
        throw new Error(`Unknown argument "${argument}".`);
    }

    index += 2;
  }

  return {
    version: normalizeRequiredValue(version, "--version"),
    arm64Sha256: normalizeRequiredValue(arm64Sha256, "--arm64-sha256"),
    x64Sha256: normalizeRequiredValue(x64Sha256, "--x64-sha256"),
    outputPath,
    owner,
    repo,
    bundleId,
  };
}

function main(): void {
  const options = parseCliOptions(process.argv.slice(2));
  const cask = generateHomebrewCask(options);
  writeOptionalFile(options.outputPath, cask);
}

if (import.meta.main) {
  main();
}
