name: Deploy Landing Site

on:
  push:
    branches:
      - main
    paths:
      - "packages/landing/**"
      - ".github/workflows/deploy-landing-site.yml"
      - ".github/workflows/_deploy-landing-site.yml"
      - "CHANGELOG.md"
      - "package.json"
      - "pnpm-lock.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: read
    uses: ./.github/workflows/_deploy-landing-site.yml
    with:
      source_sha: ${{ github.sha }}
    secrets:
      landing_github_token: ${{ secrets.NODEXAPP_GITHUB_IO_TOKEN }}
